### ISSUE TITLE
Contribute Changes Upstream?

### ISSUE THREAD

**Issue by ajsquared** [Redmart/sbt-checkstyle-plugin#2]
I'm the maintainer of the upstream https://github.com/etsy/sbt-checkstyle-plugin.  There's some great improvements here and we've had some interested in some of the changes you've made.

Would you be willing to contribute your changes back upstream?

**Comment by AlejandroRivera** [comment]
That was the original intention, but there's still a couple of issues that i haven't worked on that prevented me from trying to submit a PR. If you're interested in helping out (since i'm not sure when exactly when i'll get to work on them), i can create issues and assign them to you. LMK.

**Comment by JosephEarl** [comment]
I'm going to submit a PR for the changes @AlejandroRivera made for failing the build upstream at least, since I'm currently working around the lack of support in the "official" plugin.

**Comment by JosephEarl** [comment]
Here's a PR for upstreaming the integration test support https://github.com/etsy/sbt-checkstyle-plugin/pull/11

**Comment by JosephEarl** [comment]
I think the only major remaining the change is the ability to handle remote checkstyle files (see https://github.com/etsy/sbt-checkstyle-plugin/issues/13).

I'm not sure whether to port the implementation pretty much as is or instead change `checkstyleConfig` and `checkstyleTarget` to `String` and resolve using the logic applied by the [maven-checkstyle-plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#configLocation) - class path resource, URL, then file.

**Comment by ajsquared** [comment]
Thanks to @JosephEarl I think we're all set here.

**Comment by AlejandroRivera** [comment]
I've updated this repo to reflect that the official repo is the way to go forward. 
Thanks!
