### ISSUE TITLE
Fix scripted tests

### ISSUE THREAD

**Issue by AlejandroRivera** [Redmart/sbt-checkstyle-plugin#4]
Due to me not RTFM, i didn't realize how to correctly execute the scripted tests, thus i ran them manually.

Now that i read the Guidelines, i see `sbt test scripted` is how you do it! d'uh..

However, the scripts i wrote (trying to replicate what i saw in existing `test` files, don't seem to work as i'd expected, hence they need fixing.

**Comment by JosephEarl** [comment]
I ported checkstyle-check here https://github.com/etsy/sbt-checkstyle-plugin/pull/10 and fixed the scripted test which might help you

**Comment by JosephEarl** [comment]
This page explains the syntax http://eed3si9n.com/testing-sbt-plugins - it's not bash/shell.

**Comment by AlejandroRivera** [comment]
Sweet, thanks!
